import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Brand } from "@/components/brand";

export const metadata = { title: "About Foyer" };

export default function AboutPage() {
  return <main className="min-h-screen bg-background"><header className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Brand /><Link href="/" className="text-sm font-semibold text-muted-foreground hover:text-foreground">Back home</Link></header><section className="border-y border-border"><div className="mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">About Foyer</p><h1 className="font-display mt-6 max-w-4xl text-5xl font-semibold leading-[.92] tracking-[-.065em] sm:text-7xl">A place to be in the room, even when you are not.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground">Foyer brings live video and text together in rooms people can own, shape, and return to.</p></div></section><section className="mx-auto grid max-w-7xl gap-8 px-4 py-20 sm:px-6 md:grid-cols-3 lg:px-8"><article><h2 className="font-display text-2xl font-semibold">No audience needed</h2><p className="mt-3 leading-7 text-muted-foreground">Rooms are for friends, communities, regulars, and people with something to say.</p></article><article><h2 className="font-display text-2xl font-semibold">Built around people</h2><p className="mt-3 leading-7 text-muted-foreground">Owners set room roles and moderation boundaries instead of giving them up to an opaque feed.</p></article><article><h2 className="font-display text-2xl font-semibold">Ready when you are</h2><p className="mt-3 leading-7 text-muted-foreground">Claim a name, share a link, and let conversation take its own shape.</p></article></section><footer className="border-t border-border"><div className="mx-auto flex max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-2 text-sm font-semibold">Find a room <ArrowUpRight className="h-4 w-4" /></Link></div></footer></main>;
}
